// Include all *.h files in obj_dir (auto-generated by Verilator)
// Use `make prepare_header` to regenerate
// Top-level core header file
#include "VTop.h"
#include "VTop_Top.h"

// Root module and global unit header files
#include "VTop___024root.h"
#include "VTop___024unit.h"

// Core module related
#include "VTop_Core.h"
#include "VTop_CSR.h"

// Branch prediction related
#include "VTop_BranchPredictor__N3.h"
#include "VTop_ReturnStack.h"

// SoC and external modules
#include "VTop_SoC.h"
#include "VTop_ExternalAXISim.h"

// Instruction fetch stage related
#include "VTop_IFetch.h"
#include "VTop_IFetchPipeline.h"
#include "VTop_IF_Cache.h"
#include "VTop_IF_CTable.h"
#include "VTop_IF_ICache.h"
#include "VTop_IF_ICTable.h"
#include "VTop_IF_MMIO.h"

// Memory module related
#include "VTop_MemRTL__W200_N40.h"
#include "VTop_MemRTL__W200_N100_WB80.h"
#include "VTop_MemRTL1RW__W2_N40_WB2.h"
#include "VTop_MemRTL1RW__W54_N40_WB15.h"
#include "VTop_StoreQueue.h"
#include "VTop_ROB.h"

// Register file and rename related
#include "VTop_RegFile__NB5_A1.h"
#include "VTop_RegFile__W23_S20_N3_NB1.h"
#include "VTop_RegFile__W50_S20_N1_NB1.h"
#include "VTop_RenameTable__ND5.h"
#include "VTop_Rename__WC5.h"
#include "VTop_TagBuffer.h"

// Other auxiliary header files
#include "VTop__Dpi.h"
#include "VTop__pch.h" // Precompiled header
#include "VTop__Syms.h"