name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Fetch Submodules
      run: git submodule update --init --recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install verilator dtc
        
    - name: Build Spike
      run: |
        cd riscv-isa-sim
        ./configure
        make
        cd ..
        
    - name: Compile
      run: make

    - name: Run Hello World
      run: ./obj_dir/VTop test_programs/hello_world_spi.s
