name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Fetch Submodules
      run: git submodule update --init --recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install device-tree-compiler libfl2 libfl-dev zlib1g zlib1g-dev ccache numactl
        
    # Verilator in Ubuntu repos is very old, so build it manually.
    - name: Build Verilator 5
      run: |
        wget https://github.com/verilator/verilator/archive/refs/tags/v5.008.tar.gz
        tar -xf v5.008.tar.gz
        cd verilator-5.008
        autoconf
        ./configure
        make -j `nproc`
        sudo make install
        
    - name: Build Spike
      run: |
        cd riscv-isa-sim
        ./configure
        make -j `nproc`
        cd ..
        
    - name: Compile
      run: make -j `nproc`

    - name: Run Hello World
      run: ./obj_dir/VTop test_programs/hello_world_spi.s
